name: Test Coverage

on:
    workflow_dispatch:
    pull_request:

jobs:
    tests:
        name: Run test coverage
        runs-on: ubuntu-latest
        steps:
            - uses: reedwade/departuretimes/.github/actions/checkout-and-test@main
              with:
                coverage: true
