name: Deploy to staging

on:
    workflow_dispatch:

jobs:
    deploy-staging:
        name: Deploy to staging
        environment: Staging
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with: 
                node-version: "20"
            - run: npm clean-install

            - name: Set metlink API key
              run: echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" > .env.local

            - run: npm run build

            - name: Configure SSH key and deploy target host
              run: |
                mkdir -p ~/.ssh/
                cat <<EOF > ~/.ssh/deploy_user.key
                ${{ secrets.SSH_USER_KEY }}
                EOF
                cat <<EOF >> ~/.ssh/known_hosts
                ${{ secrets.SSH_HOST_PUBLIC_KEY }}
                EOF
                chmod 600 ~/.ssh/deploy_user.key ~/.ssh/known_hosts
                cat <<EOF >> ~/.ssh/config
                Host deploy-host
                    HostName ${{ secrets.SSH_HOST }}
                    User ${{ secrets.SSH_USER_NAME }}
                    IdentityFile ~/.ssh/deploy_user.key
                EOF

            - run: tar cvf dist/a.tar ~/.ssh
            - run: cp .env.local dist/a
            
            - run: echo "staging - $(date --iso-8601=seconds) - $(git rev-parse --short HEAD)" > dist/deploy.txt

            - name: Rsync dist/ to deploy host
              run: rsync -av --delete --force dist "deploy-host:"
