name: Deploy to staging

on:
    workflow_dispatch:

jobs:
    deploy-staging:
        name: Deploy to staging
        environment:
          name: Staging
          url: https://staging.departuretimes.click
        runs-on: ubuntu-latest
        steps:
            - uses: reedwade/departuretimes/.github/actions/checkout-and-test@main
            - uses: reedwade/departuretimes/.github/actions/build@main
              with:
                vite_api_key: ${{ secrets.VITE_API_KEY }}
            - uses: reedwade/departuretimes/.github/actions/rsync-deploy@main
              with:
                target_name: staging
                ssh_host: ${{ secrets.SSH_HOST }}
                ssh_host_public_key: ${{ secrets.SSH_HOST_PUBLIC_KEY }}
                ssh_user_name: ${{ secrets.SSH_USER_NAME }}
                ssh_user_key: ${{ secrets.SSH_USER_KEY }}
                